package at.aimon.core.llm;

import java.util.Map;
import java.util.Objects;
import java.util.function.Supplier;

/**
 * Provides dynamically generated tool definitions based on runtime context.
 *
 * <p>
 * This provider generates a new {@link ToolDefinition} each time {@link #getDefinition()} is called, using a
 * {@link Supplier} to produce the description. This allows tool descriptions to reflect current system state, such as
 * available subagents, registered commands, or other dynamic information.
 *
 * <p>
 * The tool name, category, and input schema remain constant, while the description can change based on the supplier's
 * logic.
 *
 * <p>
 * Thread-safe if the description supplier is thread-safe.
 *
 * <p>
 * Example usage:
 *
 * <pre>
 * {@code
 * SubagentRegistry registry = ...;
 *
 * ToolDefinitionProvider provider = new DynamicToolDefinitionProvider(
 *     "task",
 *     () -> {
 *         StringBuilder desc = new StringBuilder("Launch subagents. Available: ");
 *         registry.getAllSubagents().forEach(s -> desc.append(s.getName()).append(", "));
 *         return desc.toString();
 *     },
 *     Map.of(
 *         "type", "object",
 *         "properties", Map.of(
 *             "subagent_name", Map.of("type", "string"),
 *             "prompt", Map.of("type", "string")
 *         )
 *     )
 * );
 * }
 * </pre>
 *
 * @see ToolDefinitionProvider
 * @see ToolDefinition
 */
public final class DynamicToolDefinitionProvider implements ToolDefinitionProvider {
    private final String name;
    private final String category;
    private final Supplier<String> descriptionSupplier;
    private final Map<String, Object> inputSchema;

    /**
     * Creates a new DynamicToolDefinitionProvider with the default category.
     *
     * @param name
     *            The tool name (must not be null)
     * @param descriptionSupplier
     *            The supplier that generates tool descriptions (must not be null)
     * @param inputSchema
     *            The input schema in JSON Schema format (must not be null)
     * @throws NullPointerException
     *             if any parameter is null
     */
    public DynamicToolDefinitionProvider(String name, Supplier<String> descriptionSupplier,
            Map<String, Object> inputSchema) {
        this(name, ToolDefinition.DEFAULT_CATEGORY, descriptionSupplier, inputSchema);
    }

    /**
     * Creates a new DynamicToolDefinitionProvider with the specified category.
     *
     * @param name
     *            The tool name (must not be null)
     * @param category
     *            The tool category (must not be null)
     * @param descriptionSupplier
     *            The supplier that generates tool descriptions (must not be null)
     * @param inputSchema
     *            The input schema in JSON Schema format (must not be null)
     * @throws NullPointerException
     *             if any parameter is null
     */
    public DynamicToolDefinitionProvider(String name, String category, Supplier<String> descriptionSupplier,
            Map<String, Object> inputSchema) {
        this.name = Objects.requireNonNull(name, "Name cannot be null");
        this.category = Objects.requireNonNull(category, "Category cannot be null");
        this.descriptionSupplier = Objects.requireNonNull(descriptionSupplier, "Description supplier cannot be null");
        this.inputSchema = Map.copyOf(Objects.requireNonNull(inputSchema, "Input schema cannot be null"));
    }

    /**
     * Gets a dynamically generated tool definition.
     *
     * <p>
     * This method creates a new {@link ToolDefinition} on each call, with the description generated by invoking the
     * description supplier. The name, category, and input schema remain constant.
     *
     * @return A new tool definition with dynamically generated description (never null)
     */
    @Override
    public ToolDefinition getDefinition() {
        final String description = descriptionSupplier.get();
        return ToolDefinition.of(name, description, category, inputSchema);
    }

    /**
     * Gets the tool name.
     *
     * @return The tool name (never null)
     */
    public String getName() {
        return name;
    }

    /**
     * Gets the tool category.
     *
     * @return The tool category (never null)
     */
    public String getCategory() {
        return category;
    }

    /**
     * Gets the input schema.
     *
     * @return An immutable map containing the JSON Schema (never null)
     */
    public Map<String, Object> getInputSchema() {
        return inputSchema;
    }

    @Override
    public String toString() {
        return "DynamicToolDefinitionProvider{name='" + name + "', category='" + category + "', inputSchema="
                + inputSchema + '}';
    }
}
