package at.aimon.core.llm;

import java.util.Objects;
import java.util.Optional;

import at.aimon.core.base.ArtifactMetadata;

/**
 * Immutable metadata reference to a file artifact produced during tool execution.
 *
 * <p>
 * This is a lightweight value object stored within {@link Message} to track which files were generated by tool uses
 * within a conversation turn. Actual file content resides in the VirtualFileSystem; this object holds only metadata.
 *
 * <p>
 * Example usage:
 *
 * <pre>
 * {
 *     &#64;code
 *     MessageArtifact artifact = MessageArtifact.builder().path("/reports/sales-2024.csv").fileName("sales-2024.csv")
 *             .size(15360).mimeType("text/csv").toolUseId("toolu_abc123").build();
 * }
 * </pre>
 *
 * @see Message#getArtifacts()
 * @see ArtifactMetadata
 */
public final class MessageArtifact implements ArtifactMetadata {

    private final String path;
    private final String fileName;
    private final long size;
    private final String mimeType;
    private final String toolUseId;
    private final String downloadToken;

    private MessageArtifact(Builder builder) {
        this.path = requireNonBlank(builder.path, "Path cannot be null or blank");
        this.fileName = requireNonBlank(builder.fileName, "File name cannot be null or blank");
        if (builder.size < 0) {
            throw new IllegalArgumentException("Size must be non-negative, got: " + builder.size);
        }
        this.size = builder.size;
        this.mimeType = builder.mimeType;
        this.toolUseId = builder.toolUseId;
        this.downloadToken = builder.downloadToken;
    }

    private static String requireNonBlank(String value, String message) {
        Objects.requireNonNull(value, message);
        if (value.isBlank()) {
            throw new IllegalArgumentException(message);
        }
        return value;
    }

    /**
     * Creates a new builder.
     *
     * @return A new MessageArtifact.Builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Gets the VirtualFileSystem path.
     *
     * @return The file path (never null)
     */
    public String getPath() {
        return path;
    }

    /**
     * Gets the file name for user display.
     *
     * @return The file name (never null)
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Gets the file size in bytes.
     *
     * @return The file size (non-negative)
     */
    public long getSize() {
        return size;
    }

    /**
     * Gets the MIME type.
     *
     * @return The MIME type, or empty if unknown
     */
    public Optional<String> getMimeType() {
        return Optional.ofNullable(mimeType);
    }

    /**
     * Gets the tool use ID that created this artifact.
     *
     * @return The tool use ID, or empty if not tracked
     */
    public Optional<String> getToolUseId() {
        return Optional.ofNullable(toolUseId);
    }

    /**
     * Gets the download token for linking to download storage.
     *
     * @return The download token, or empty if not set
     */
    @Override
    public Optional<String> getDownloadToken() {
        return Optional.ofNullable(downloadToken);
    }

    /**
     * Returns a new MessageArtifact with the given download token set.
     *
     * @param downloadToken
     *            The download token (nullable)
     * @return A new MessageArtifact with the download token
     */
    public MessageArtifact withDownloadToken(String downloadToken) {
        return MessageArtifact.builder().path(this.path).fileName(this.fileName).size(this.size).mimeType(this.mimeType)
                .toolUseId(this.toolUseId).downloadToken(downloadToken).build();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final MessageArtifact that = (MessageArtifact) o;
        return size == that.size && path.equals(that.path) && fileName.equals(that.fileName)
                && Objects.equals(mimeType, that.mimeType) && Objects.equals(toolUseId, that.toolUseId)
                && Objects.equals(downloadToken, that.downloadToken);
    }

    @Override
    public int hashCode() {
        return Objects.hash(path, fileName, size, mimeType, toolUseId, downloadToken);
    }

    @Override
    public String toString() {
        return "MessageArtifact{" + "path='" + path + '\'' + ", fileName='" + fileName + '\'' + ", size=" + size
                + ", mimeType='" + mimeType + '\'' + ", toolUseId='" + toolUseId + '\'' + ", downloadToken='"
                + downloadToken + '\'' + '}';
    }

    /**
     * Builder for constructing {@link MessageArtifact} instances.
     *
     * <p>
     * Required fields: {@code path}, {@code fileName}. The {@code size} must be non-negative (defaults to 0).
     * {@code mimeType}, {@code toolUseId} and {@code downloadToken} are optional.
     */
    public static final class Builder {
        private String path;
        private String fileName;
        private long size;
        private String mimeType;
        private String toolUseId;
        private String downloadToken;

        private Builder() {
        }

        /**
         * Sets the VirtualFileSystem path.
         *
         * @param path
         *            The file path (must not be null or blank)
         * @return This builder
         */
        public Builder path(String path) {
            this.path = path;
            return this;
        }

        /**
         * Sets the file name for user display.
         *
         * @param fileName
         *            The file name (must not be null or blank)
         * @return This builder
         */
        public Builder fileName(String fileName) {
            this.fileName = fileName;
            return this;
        }

        /**
         * Sets the file size in bytes.
         *
         * @param size
         *            The file size (must be non-negative)
         * @return This builder
         */
        public Builder size(long size) {
            this.size = size;
            return this;
        }

        /**
         * Sets the MIME type.
         *
         * @param mimeType
         *            The MIME type (nullable)
         * @return This builder
         */
        public Builder mimeType(String mimeType) {
            this.mimeType = mimeType;
            return this;
        }

        /**
         * Sets the tool use ID that created this artifact.
         *
         * @param toolUseId
         *            The tool use ID (nullable)
         * @return This builder
         */
        public Builder toolUseId(String toolUseId) {
            this.toolUseId = toolUseId;
            return this;
        }

        /**
         * Sets the download token for linking to download storage.
         *
         * @param downloadToken
         *            The download token (nullable)
         * @return This builder
         */
        public Builder downloadToken(String downloadToken) {
            this.downloadToken = downloadToken;
            return this;
        }

        /**
         * Builds a new {@link MessageArtifact}.
         *
         * @return A new MessageArtifact
         * @throws NullPointerException
         *             if path or fileName is null
         * @throws IllegalArgumentException
         *             if path or fileName is blank, or size is negative
         */
        public MessageArtifact build() {
            return new MessageArtifact(this);
        }
    }
}
