package at.aimon.core.agent.queue;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.time.Instant;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import at.aimon.core.agent.AgentRuntimeId;
import at.aimon.core.agent.AgentRuntimeIds;

@DisplayName("QueuedInput Tests")
class QueuedInputTest {

    private static final AgentRuntimeId CTX = AgentRuntimeIds.testCtx("ctx-1");

    private static QueuedInput.Builder baseBuilder() {
        return QueuedInput.builder().inputText("hello").agentRuntimeId(CTX);
    }

    @Nested
    @DisplayName("Builder defaults")
    class BuilderDefaults {

        @Test
        @DisplayName("uuid is auto-generated and unique per builder invocation")
        void uuidIsAutoGenerated() {
            QueuedInput a = baseBuilder().build();
            QueuedInput b = baseBuilder().build();

            assertThat(a.getUuid()).isNotNull();
            assertThat(b.getUuid()).isNotNull();
            assertThat(a.getUuid()).isNotEqualTo(b.getUuid());
        }

        @Test
        @DisplayName("priority defaults to NEXT")
        void priorityDefaultsToNext() {
            QueuedInput input = baseBuilder().build();
            assertThat(input.getPriority()).isEqualTo(QueuedInputPriority.NEXT);
        }

        @Test
        @DisplayName("enqueuedAt defaults to now (non-null)")
        void enqueuedAtDefaultsToNow() {
            Instant before = Instant.now().minusSeconds(1);
            QueuedInput input = baseBuilder().build();
            Instant after = Instant.now().plusSeconds(1);

            assertThat(input.getEnqueuedAt()).isNotNull();
            assertThat(input.getEnqueuedAt()).isBetween(before, after);
        }

        @Test
        @DisplayName("sourceAgentId defaults to empty Optional")
        void sourceAgentIdDefaultsToEmpty() {
            QueuedInput input = baseBuilder().build();
            assertThat(input.getSourceAgentId()).isEmpty();
        }

        @Test
        @DisplayName("metadata defaults to an empty map")
        void metadataDefaultsToEmpty() {
            QueuedInput input = baseBuilder().build();
            assertThat(input.getMetadata()).isEmpty();
        }
    }

    @Nested
    @DisplayName("Null checks")
    class NullChecks {

        @Test
        @DisplayName("inputText is required")
        void inputTextRequired() {
            assertThatThrownBy(() -> QueuedInput.builder().agentRuntimeId(CTX).build())
                    .isInstanceOf(NullPointerException.class).hasMessageContaining("inputText");
        }

        @Test
        @DisplayName("inputText must not be empty")
        void inputTextNotEmpty() {
            assertThatThrownBy(() -> baseBuilder().inputText("").build()).isInstanceOf(IllegalArgumentException.class)
                    .hasMessageContaining("inputText");
        }

        @Test
        @DisplayName("agentRuntimeId is required")
        void agentRuntimeIdRequired() {
            assertThatThrownBy(() -> QueuedInput.builder().inputText("x").build())
                    .isInstanceOf(NullPointerException.class).hasMessageContaining("agentRuntimeId");
        }

        @Test
        @DisplayName("priority setter rejects null")
        void prioritySetterRejectsNull() {
            assertThatThrownBy(() -> baseBuilder().priority(null).build()).isInstanceOf(NullPointerException.class)
                    .hasMessageContaining("priority");
        }

        @Test
        @DisplayName("metadata setter rejects null map")
        void metadataSetterRejectsNull() {
            assertThatThrownBy(() -> baseBuilder().metadata(null).build()).isInstanceOf(NullPointerException.class)
                    .hasMessageContaining("metadata");
        }

        @Test
        @DisplayName("uuid setter rejects null")
        void uuidSetterRejectsNull() {
            assertThatThrownBy(() -> baseBuilder().uuid(null).build()).isInstanceOf(NullPointerException.class)
                    .hasMessageContaining("uuid");
        }

        @Test
        @DisplayName("enqueuedAt setter rejects null")
        void enqueuedAtSetterRejectsNull() {
            assertThatThrownBy(() -> baseBuilder().enqueuedAt(null).build()).isInstanceOf(NullPointerException.class)
                    .hasMessageContaining("enqueuedAt");
        }
    }

    @Nested
    @DisplayName("Defensive copy of metadata")
    class DefensiveCopy {

        @Test
        @DisplayName("later mutations to source map do not affect the built input")
        void sourceMutationsIgnored() {
            Map<String, String> source = new HashMap<>();
            source.put("k", "v1");

            QueuedInput input = baseBuilder().metadata(source).build();
            source.put("k", "v2");
            source.put("new", "added");

            assertThat(input.getMetadata()).containsExactly(Map.entry("k", "v1"));
        }

        @Test
        @DisplayName("returned metadata map is unmodifiable")
        void returnedMapUnmodifiable() {
            QueuedInput input = baseBuilder().metadata(Map.of("k", "v")).build();
            assertThatThrownBy(() -> input.getMetadata().put("x", "y"))
                    .isInstanceOf(UnsupportedOperationException.class);
        }
    }

    @Nested
    @DisplayName("Equality and hashCode")
    class EqualityTests {

        @Test
        @DisplayName("inputs with the same uuid are equal (regardless of other fields)")
        void equalityByUuid() {
            UUID uuid = UUID.randomUUID();
            QueuedInput a = baseBuilder().uuid(uuid).inputText("one").priority(QueuedInputPriority.NOW).build();
            QueuedInput b = baseBuilder().uuid(uuid).inputText("two").priority(QueuedInputPriority.LATER).build();

            assertThat(a).isEqualTo(b);
            assertThat(a.hashCode()).isEqualTo(b.hashCode());
        }

        @Test
        @DisplayName("inputs with different uuids are not equal")
        void inequalityByUuid() {
            QueuedInput a = baseBuilder().build();
            QueuedInput b = baseBuilder().build();

            assertThat(a).isNotEqualTo(b);
        }

        @Test
        @DisplayName("equals is symmetric, reflexive, and null-safe")
        void equalsContract() {
            QueuedInput a = baseBuilder().build();

            assertThat(a).isEqualTo(a);
            assertThat(a).isNotEqualTo(null);
            assertThat(a).isNotEqualTo("not a QueuedInput");
        }
    }

    @Nested
    @DisplayName("toString")
    class ToStringTests {

        @Test
        @DisplayName("truncates long inputText to 40 chars with ellipsis")
        void truncatesLongText() {
            String fortyOne = "a".repeat(41);
            QueuedInput input = baseBuilder().inputText(fortyOne).build();

            assertThat(input.toString()).contains("a".repeat(40) + "…");
            assertThat(input.toString()).doesNotContain(fortyOne);
        }

        @Test
        @DisplayName("keeps short inputText intact")
        void shortTextKeptIntact() {
            QueuedInput input = baseBuilder().inputText("short").build();
            assertThat(input.toString()).contains("short");
            assertThat(input.toString()).doesNotContain("…");
        }

        @Test
        @DisplayName("keeps exactly-40-char inputText without truncation")
        void exactlyFortyCharsNotTruncated() {
            String forty = "a".repeat(40);
            QueuedInput input = baseBuilder().inputText(forty).build();

            assertThat(input.toString()).contains(forty);
            assertThat(input.toString()).doesNotContain("…");
        }
    }
}
